const skins = [
  { skinname: "Divergence", price: 8700, image: "images/divergence.webp" },
  {
    skinname: "Bubblegum Deathwish",
    price: 8700,
    image: "images/bubblegum.webp",
  },
  { skinname: "Doombringer", price: 8700, image: "images/doombringer.webp" },
  { skinname: "Evori Dreamwings", price: 9900, image: "images/evori.webp" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
  { skinname: "a", price: 0, image: "img" },
];
